# Generated by Django 2.0.3 on 2018-03-28 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_dogbreed'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogbreed',
            name='image_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='dogbreed',
            name='size',
            field=models.CharField(choices=[('MI', 'Miniature'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('G', 'Giant')], default='MED', max_length=6),
        ),
    ]
