# Generated by Django 2.0.2 on 2018-06-12 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20180605_0848'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player_Scores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('current_question', models.IntegerField()),
                ('score', models.IntegerField()),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Tournament')),
            ],
        ),
    ]
