# Generated by Django 2.0.3 on 2018-03-28 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogBreed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(choices=[('MI', 'Afghan Hound'), ('MI', 'Basset Hound'), ('MI', 'Beagle'), ('MI', 'Bichon Frise'), ('MI', 'Borzoi'), ('MI', 'Bull Dog'), ('MI', 'Cavalier King Charles Spaniel'), ('MI', 'Chow Chow'), ('MI', 'Dalmation'), ('MI', 'Golden Retriever'), ('MI', 'Maltese'), ('MI', 'Newfoundland'), ('MI', 'Old English Sheepdog'), ('MI', 'Pug'), ('MI', 'West Highland White Terrier')], default='MED', max_length=6)),
                ('activity_level', models.CharField(choices=[('LOW', 'Low'), ('MED', 'Medium'), ('HIGH', 'High')], default='MED', max_length=6)),
                ('shedding_level', models.CharField(choices=[('LOW', 'Low'), ('MED', 'Medium'), ('HIGH', 'High')], default='MED', max_length=6)),
                ('grooming_level', models.CharField(choices=[('LOW', 'Low'), ('MED', 'Medium'), ('HIGH', 'High')], default='MED', max_length=6)),
                ('intelligence', models.CharField(choices=[('LOW', 'Low'), ('MED', 'Medium'), ('HIGH', 'High')], default='MED', max_length=6)),
                ('good_with_children', models.CharField(choices=[('YES', 'Yes'), ('NO', 'NHo')], default='MED', max_length=6)),
                ('drools', models.CharField(choices=[('YES', 'Yes'), ('NO', 'NHo')], default='MED', max_length=6)),
                ('coat_length', models.CharField(choices=[('LOW', 'Low'), ('MED', 'Medium'), ('HIGH', 'High')], default='MED', max_length=6)),
                ('size', models.CharField(default='MED', max_length=100)),
            ],
        ),
    ]
