# Generated by Django 2.0.4 on 2018-05-28 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20180403_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('start_date', models.CharField(default=datetime.datetime(2018, 5, 28, 23, 23, 48, 142365), max_length=6)),
                ('end_date', models.CharField(default=datetime.datetime(2018, 5, 29, 23, 23, 48, 142365), max_length=6)),
                ('category', models.CharField(choices=[('Any', 'Any Category'), ('General Knowledge', 'General Knowledge'), ('Books', 'Entertainment: Books'), ('Film', 'Entertainment: Film'), ('Music', 'Entertainment: Music'), ('Music&Theatres', 'Entertainment: Musicals & Theatres'), ('Television', 'Entertainment: Television'), ('Video Games', 'Entertainment: Video Games'), ('Board Games', 'Entertainment: Board Games'), ('Science & Nature', 'Science & Nature'), ('Science: Computers', 'Science: Computers'), ('Mathematics', 'Science: Mathematics'), ('Mythology', 'Mythology'), ('Sports', 'Sports'), ('Geography', 'Geography'), ('History', 'History'), ('Politics', 'Politics'), ('Art', 'Art'), ('Celebrities', 'Celebrities'), ('Animals', 'Animals'), ('Vehicles', 'Vehicles'), ('Comics', 'Entertainment: Comics'), ('Gadgets', 'Science: Gadgets'), ('Japanese Anime & Manga', 'Entertainment: Japanese Anime & Manga'), ('Cartoon & Animations', 'Entertainment: Cartoon & Animations')], default='Any Category', max_length=6)),
                ('difficulty', models.CharField(choices=[('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard')], default='Easy', max_length=6)),
            ],
        ),
        migrations.DeleteModel(
            name='DogBreed',
        ),
    ]
