# Generated by Django 2.0.2 on 2018-05-30 21:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20180531_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2018, 6, 1, 9, 12, 47, 136023)),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2018, 5, 31, 9, 12, 47, 136023)),
        ),
    ]
