# Generated by Django 2.0.2 on 2018-06-12 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_player_scores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_scores',
            name='tournament',
            field=models.IntegerField(),
        ),
    ]
